# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import explorer_pb2 as explorer__pb2
import okchain_pb2 as okchain__pb2


class BackendStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetNetworkInfo = channel.unary_unary(
        '/protos.Backend/GetNetworkInfo',
        request_serializer=explorer__pb2.NetworkInfoRequest.SerializeToString,
        response_deserializer=explorer__pb2.NetworkInfoResponse.FromString,
        )
    self.GetAccount = channel.unary_unary(
        '/protos.Backend/GetAccount',
        request_serializer=explorer__pb2.AccountRequest.SerializeToString,
        response_deserializer=explorer__pb2.AccountResponse.FromString,
        )
    self.GetDsBlock = channel.unary_unary(
        '/protos.Backend/GetDsBlock',
        request_serializer=explorer__pb2.DsBlockRequest.SerializeToString,
        response_deserializer=okchain__pb2.DSBlock.FromString,
        )
    self.GetTxBlock = channel.unary_unary(
        '/protos.Backend/GetTxBlock',
        request_serializer=explorer__pb2.TxBlockRequest.SerializeToString,
        response_deserializer=okchain__pb2.TxBlock.FromString,
        )
    self.GetTransaction = channel.unary_unary(
        '/protos.Backend/GetTransaction',
        request_serializer=explorer__pb2.TransactionRequest.SerializeToString,
        response_deserializer=okchain__pb2.Transaction.FromString,
        )
    self.GetRecentTransactions = channel.unary_unary(
        '/protos.Backend/GetRecentTransactions',
        request_serializer=explorer__pb2.RecentTransactionsRequest.SerializeToString,
        response_deserializer=explorer__pb2.RecentTransactionsResponse.FromString,
        )
    self.GetTransactionsByAccount = channel.unary_unary(
        '/protos.Backend/GetTransactionsByAccount',
        request_serializer=explorer__pb2.GetTransactionsByAccountRequest.SerializeToString,
        response_deserializer=explorer__pb2.GetTransactionsByAccountResponse.FromString,
        )
    self.GetLatestDsBlock = channel.unary_unary(
        '/protos.Backend/GetLatestDsBlock',
        request_serializer=explorer__pb2.EmptyRequest.SerializeToString,
        response_deserializer=okchain__pb2.DSBlock.FromString,
        )
    self.GetLatestTxBlock = channel.unary_unary(
        '/protos.Backend/GetLatestTxBlock',
        request_serializer=explorer__pb2.EmptyRequest.SerializeToString,
        response_deserializer=okchain__pb2.TxBlock.FromString,
        )
    self.RegisterAccount = channel.unary_unary(
        '/protos.Backend/RegisterAccount',
        request_serializer=explorer__pb2.RegisterAccountRequest.SerializeToString,
        response_deserializer=explorer__pb2.RegisterAccountResponse.FromString,
        )
    self.SendTransaction = channel.unary_unary(
        '/protos.Backend/SendTransaction',
        request_serializer=okchain__pb2.Transaction.SerializeToString,
        response_deserializer=explorer__pb2.TransactionResponse.FromString,
        )
    self.Notify = channel.unary_unary(
        '/protos.Backend/Notify',
        request_serializer=okchain__pb2.Message.SerializeToString,
        response_deserializer=okchain__pb2.ConfigRpcResponse.FromString,
        )


class BackendServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetNetworkInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDsBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTxBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRecentTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionsByAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLatestDsBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLatestTxBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Notify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BackendServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetNetworkInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetNetworkInfo,
          request_deserializer=explorer__pb2.NetworkInfoRequest.FromString,
          response_serializer=explorer__pb2.NetworkInfoResponse.SerializeToString,
      ),
      'GetAccount': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccount,
          request_deserializer=explorer__pb2.AccountRequest.FromString,
          response_serializer=explorer__pb2.AccountResponse.SerializeToString,
      ),
      'GetDsBlock': grpc.unary_unary_rpc_method_handler(
          servicer.GetDsBlock,
          request_deserializer=explorer__pb2.DsBlockRequest.FromString,
          response_serializer=okchain__pb2.DSBlock.SerializeToString,
      ),
      'GetTxBlock': grpc.unary_unary_rpc_method_handler(
          servicer.GetTxBlock,
          request_deserializer=explorer__pb2.TxBlockRequest.FromString,
          response_serializer=okchain__pb2.TxBlock.SerializeToString,
      ),
      'GetTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransaction,
          request_deserializer=explorer__pb2.TransactionRequest.FromString,
          response_serializer=okchain__pb2.Transaction.SerializeToString,
      ),
      'GetRecentTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.GetRecentTransactions,
          request_deserializer=explorer__pb2.RecentTransactionsRequest.FromString,
          response_serializer=explorer__pb2.RecentTransactionsResponse.SerializeToString,
      ),
      'GetTransactionsByAccount': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionsByAccount,
          request_deserializer=explorer__pb2.GetTransactionsByAccountRequest.FromString,
          response_serializer=explorer__pb2.GetTransactionsByAccountResponse.SerializeToString,
      ),
      'GetLatestDsBlock': grpc.unary_unary_rpc_method_handler(
          servicer.GetLatestDsBlock,
          request_deserializer=explorer__pb2.EmptyRequest.FromString,
          response_serializer=okchain__pb2.DSBlock.SerializeToString,
      ),
      'GetLatestTxBlock': grpc.unary_unary_rpc_method_handler(
          servicer.GetLatestTxBlock,
          request_deserializer=explorer__pb2.EmptyRequest.FromString,
          response_serializer=okchain__pb2.TxBlock.SerializeToString,
      ),
      'RegisterAccount': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterAccount,
          request_deserializer=explorer__pb2.RegisterAccountRequest.FromString,
          response_serializer=explorer__pb2.RegisterAccountResponse.SerializeToString,
      ),
      'SendTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.SendTransaction,
          request_deserializer=okchain__pb2.Transaction.FromString,
          response_serializer=explorer__pb2.TransactionResponse.SerializeToString,
      ),
      'Notify': grpc.unary_unary_rpc_method_handler(
          servicer.Notify,
          request_deserializer=okchain__pb2.Message.FromString,
          response_serializer=okchain__pb2.ConfigRpcResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.Backend', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
