# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message_pb2 as message__pb2


class GossipStub(object):
  """Gossip
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GossipStream = channel.stream_stream(
        '/protos.Gossip/GossipStream',
        request_serializer=message__pb2.Envelope.SerializeToString,
        response_deserializer=message__pb2.Envelope.FromString,
        )
    self.GossipPriStream = channel.stream_stream(
        '/protos.Gossip/GossipPriStream',
        request_serializer=message__pb2.Envelope.SerializeToString,
        response_deserializer=message__pb2.Envelope.FromString,
        )
    self.Ping = channel.unary_unary(
        '/protos.Gossip/Ping',
        request_serializer=message__pb2.Empty.SerializeToString,
        response_deserializer=message__pb2.Empty.FromString,
        )


class GossipServicer(object):
  """Gossip
  """

  def GossipStream(self, request_iterator, context):
    """GossipStream is the gRPC stream used for sending and receiving messages
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GossipPriStream(self, request_iterator, context):
    """Gossip Priority stream
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Ping(self, request, context):
    """Ping is used to probe a remote peer's aliveness
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GossipServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GossipStream': grpc.stream_stream_rpc_method_handler(
          servicer.GossipStream,
          request_deserializer=message__pb2.Envelope.FromString,
          response_serializer=message__pb2.Envelope.SerializeToString,
      ),
      'GossipPriStream': grpc.stream_stream_rpc_method_handler(
          servicer.GossipPriStream,
          request_deserializer=message__pb2.Envelope.FromString,
          response_serializer=message__pb2.Envelope.SerializeToString,
      ),
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=message__pb2.Empty.FromString,
          response_serializer=message__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.Gossip', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
